-- Migration: add_indexes
-- This is a create-only SQL migration generated by the assistant
-- It adds the indexes declared in prisma/schema.prisma

-- Create indexes if the corresponding table exists. This handles databases
-- where Prisma previously created lowercase unquoted table names or quoted
-- PascalCase names. We check for both variants and create indexes against
-- whichever table exists.

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Session') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_userid ON "Session" ("userId")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_expiresat ON "Session" ("expiresAt")';
	ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'session') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_userid ON session ("userId")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_expiresat ON session ("expiresAt")';
	END IF;
END$$;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'File') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_file_userid ON "File" ("userId")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_file_userid_createdat ON "File" ("userId", "createdAt")';
	ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'file') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_file_userid ON file ("userId")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_file_userid_createdat ON file ("userId", "createdAt")';
	END IF;
END$$;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'ShareLink') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_sharelink_token ON "ShareLink" ("token")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_sharelink_createdbyid ON "ShareLink" ("createdById")';
	ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sharelink') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_sharelink_token ON sharelink ("token")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_sharelink_createdbyid ON sharelink ("createdById")';
	END IF;
END$$;

DO $$
BEGIN
	IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AnalyticsEvent') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_analytic_userid_eventtype ON "AnalyticsEvent" ("userId", "eventType")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_analytic_eventtype_createdat ON "AnalyticsEvent" ("eventType", "createdAt")';
	ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'analyticsevent') THEN
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_analytic_userid_eventtype ON analyticsevent ("userId", "eventType")';
		EXECUTE 'CREATE INDEX IF NOT EXISTS idx_analytic_eventtype_createdat ON analyticsevent ("eventType", "createdAt")';
	END IF;
END$$;

-- End of migration
